### ISSUE TITLE
Consider changing the Docker image to Alpine Linux

### ISSUE THREAD

**Issue by RoastVeg** [michaelkamprath/multi-service-rtmp-broadcaster#1]
The current docker image clocks in at 634MB, which is very large. It's likely that massive savings could be made by switching from `ubuntu:bionic`, but I'm not sure if all the required dependencies are available for RTMP.

**Comment by michaelkamprath** [comment]
@RoastVeg I agree, but size wasn't my first priority for the first version. I will address that soon. Another source of bloat is that to enable RTMP, I have to compile nginx during the docker build, but I don't delete the compilation artifacts. 

I will keep this issue open until I get a chance to address it (or someone creates a PR for this issue).
