### ISSUE TITLE
Error running in Unraid Docker

### ISSUE THREAD

**Issue by hoveeman** [michaelkamprath/multi-service-rtmp-broadcaster#2]
I set up a container in Unraid, but am unfortunately receiving an error when I start the container. I set up the container with active stream keys from both youtube and facebook. This is the error that I receive when I try to start the container:

`nginx: [emerg] directive "push" is not terminated by ";" in /usr/local/nginx/conf/nginx.conf:156`

Here are some screenshots of my settings.

<img width="1069" alt="Screen Shot 2020-03-31 at 9 12 15 AM" src="https://user-images.githubusercontent.com/18269595/78030389-018f1480-7330-11ea-823b-22cc3a5c583f.png">

<img width="1253" alt="Screen Shot 2020-03-31 at 9 12 44 AM" src="https://user-images.githubusercontent.com/18269595/78030403-0784f580-7330-11ea-9ead-b4bdd700f270.png">

**Comment by michaelkamprath** [comment]
@hoveeman Sorry about that. A typo bug somehow made itty into the YouTube config. I have fixed it, and pushed an updated image to my repo.
