### ISSUE TITLE
Raspberry pi

### ISSUE THREAD

**Issue by Nesslax** [michaelkamprath/multi-service-rtmp-broadcaster#27]
Hello ,
I am currently trying to run your project on a raspberry pi and it failed at building step 

Step 9/25 : RUN set -x  && addgroup -S stunnel  && adduser -S -D -H -h /dev/null -s /sbin/nologin -G stunnel -g stunnel stunnel  && echo "http://dl-3.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories  && apk update  && apk add --no-cache --update stunnel ca-certificates  && apk add --no-cache pcre openssl stunnel gettext python3  && apk add --no-cache --virtual build-deps build-base pcre-dev openssl-dev zlib zlib-dev wget make  && wget -O nginx-${NGINX_VERSION}.tar.gz http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz  && tar -zxvf nginx-${NGINX_VERSION}.tar.gz  && wget -O nginx-rtmp-module-${RTMP_MODULE_VERSION}.tar.gz https://github.com/${RTMP_REPO}/nginx-rtmp-module/archive/${RTMP_MODULE_VERSION}.tar.gz  && tar -zxvf nginx-rtmp-module-${RTMP_MODULE_VERSION}.tar.gz  && cd nginx-${NGINX_VERSION}  && export CFLAGS=-Wno-error  && ./configure --with-http_ssl_module --add-module=../nginx-rtmp-module-${RTMP_MODULE_VERSION}  && make  && make install  && cp /nginx-rtmp-module-${RTMP_MODULE_VERSION}/stat.xsl /usr/local/nginx/html/  && apk del build-deps  && mkdir -p /var/www/html/recordings  && mkdir -p /var/run/stunnel/  && chown nobody:nobody -R /var/www/html  && chown stunnel:stunnel /var/run/stunnel/  && wget -O /tini https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-static  && chmod +x /tini  && pip3 install supervisor==${SUPERVISORD_VERSION} pipenv==${PIPENV_PACKAGE_VERSION}
 ---> Running in 3191d928d709
standard_init_linux.go:211: exec user process caused "exec format error"
The command '/bin/sh -c set -x  && addgroup -S stunnel  && adduser -S -D -H -h /dev/null -s /sbin/nologin -G stunnel -g stunnel stunnel  && echo "http://dl-3.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories  && apk update  && apk add --no-cache --update stunnel ca-certificates  && apk add --no-cache pcre openssl stunnel gettext python3  && apk add --no-cache --virtual build-deps build-base pcre-dev openssl-dev zlib zlib-dev wget make  && wget -O nginx-${NGINX_VERSION}.tar.gz http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz  && tar -zxvf nginx-${NGINX_VERSION}.tar.gz  && wget -O nginx-rtmp-module-${RTMP_MODULE_VERSION}.tar.gz https://github.com/${RTMP_REPO}/nginx-rtmp-module/archive/${RTMP_MODULE_VERSION}.tar.gz  && tar -zxvf nginx-rtmp-module-${RTMP_MODULE_VERSION}.tar.gz  && cd nginx-${NGINX_VERSION}  && export CFLAGS=-Wno-error  && ./configure --with-http_ssl_module --add-module=../nginx-rtmp-module-${RTMP_MODULE_VERSION}  && make  && make install  && cp /nginx-rtmp-module-${RTMP_MODULE_VERSION}/stat.xsl /usr/local/nginx/html/  && apk del build-deps  && mkdir -p /var/www/html/recordings  && mkdir -p /var/run/stunnel/  && chown nobody:nobody -R /var/www/html  && chown stunnel:stunnel /var/run/stunnel/  && wget -O /tini https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-static  && chmod +x /tini  && pip3 install supervisor==${SUPERVISORD_VERSION} pipenv==${PIPENV_PACKAGE_VERSION}' returned a non-zero code: 1

Do you have any idea how I can fix it ? 

The best

**Comment by michaelkamprath** [comment]
It likely failed building on a Raspberry PI because one or more of the packages the Docker file is trying to install in the image are not built for the ARM CPU. This docker was designed for x86 CPUs. No testing or validation was done for other CPUs.
