### ISSUE TITLE
Add capabitlity for Microsoft Stream

### ISSUE THREAD

**Issue by hoveeman** [michaelkamprath/multi-service-rtmp-broadcaster#5]
I would love to have the ability to stream to Microsoft Stream. Their rtmp url is a little different than other providers.

Here is an example URL with keys removed:

`rtmp://randomkeypervideo1-randomkeypervideo2-usea.channel.media.azure.net:1935/live/randomkeypervideo3`

These are their documents on how to setup encoders for their streams.
[Live Encoder Setup](https://docs.microsoft.com/en-us/stream/live-encoder-setup)
[Live Encoder Configuration](https://docs.microsoft.com/en-us/stream/live-encoder-configuration)

When I set up a Microsoft Stream in OBS, I copy the whole RTMP Url and paste it in Custom URL. I then type in anything I want in the Key field. So I usually type in 'stream'.

**Comment by hoveeman** [comment]
I added the custom piece to the pull request, but I'm still unable to get Microsoft Stream to work. Do you happen to know where logging is located inside the container? I checked the nginx.conf file in /usr/local/nginx/conf and it is correct and I also checked logs in /usr/local/nginx/logs, but there wasn't much help there. Not sure why it is failing on Microsoft Stream, but not on others under the Custom URL.

**Comment by michaelkamprath** [comment]
@hoveeman Note that the current configuration file [does not turn on logging](https://github.com/michaelkamprath/multi-service-rtmp-broadcaster/blob/master/multistreaming-server/nginx-conf/nginx-conf-prefix.txt#L15). You need to turn that on then try again.

**Comment by hoveeman** [comment]
I added a Pull Request #7 which adds Microsoft Stream Capability.
